name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '**.md'
      - '**.xml'

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      NATIVE_TARGET: "arm64-v8a"
      ANDROID_SDK_ROOT: /opt/android-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Set up Android SDK Tools
        uses: android-actions/setup-android@v3
        with:
          packages: "build-tools;36.0.0 ndk;26.2.11394342 platforms;android-36 cmake;3.22.1"
      - name: Configure Android SDK Path
        run: |
          export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-/opt/android-sdk}}"
          echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties
      - name: Clean build artifacts
        run: ./gradlew clean --quiet

      - name: Debug Build
        run: |
          export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
          export DEBUG_BUILD=true
          sed -i 's/signingConfig = signingConfigs.release//g' TMessagesProj/build.gradle
          ./gradlew TMessagesProj:assembleDebug --quiet

          APK=$(find TMessagesProj/build/outputs/apk -name '*arm64-v8a*.apk')
          APK=$(dirname $APK)
          echo "APK=$APK" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: Debug
          path: ${{ env.APK }}
