name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '**.md'
      - '**.xml'

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      NATIVE_TARGET: "arm64-v8a"
      ANDROID_SDK_ROOT: /opt/android-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Set up Android SDK Tools
        uses: android-actions/setup-android@v3
        with:
          packages: "build-tools;36.0.0 cmake;3.31.6 ndk;27.2.12479018 platforms;android-36"
      - name: Configure Android SDK Path
        run: |
          export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-/opt/android-sdk}}"
          echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties
      - name: Modify Gradle JVM Args
        run: |
          MEMORY_KB=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
          MEMORY_GB=$((MEMORY_KB / 1024 / 1024))
          echo "Detected memory size: ${MEMORY_GB}GB"
          if [ $MEMORY_GB -ge 12 ]; then
            sed -i '/^org\.gradle\.jvmargs=/d' gradle.properties
            echo "org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=2G -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> gradle.properties
          fi
          cat gradle.properties
      - name: Clean build artifacts
        run: ./gradlew clean --no-daemon

      - name: Debug Build
        run: |
          export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
          export DEBUG_BUILD=true
          echo "GRADLE_OPTS=${GRADLE_OPTS}"
          sed -i 's/signingConfig = signingConfigs.release//g' TMessagesProj/build.gradle
          ./gradlew TMessagesProj:assembleDebug --no-daemon --stacktrace

          APK=$(find TMessagesProj/build/outputs/apk -name '*arm64-v8a*.apk')
          APK=$(dirname $APK)
          echo "APK=$APK" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: Debug
          path: ${{ env.APK }}
